version: '3'

tasks:
  start:
    cmds:
      - 'go run ./cmd/server/main.go'
  lint:
    cmds:
      - 'gofmt -s -w .'
  update_docs:
    cmds:
      - 'swag fmt ./'
      - 'swag init -ot json -g ./cmd/server/main.go' 
